//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Generators.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Generators.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///  &quot;title&quot;: &quot;Catalog&quot;,
        ///  &quot;type&quot;: &quot;object&quot;,
        ///  &quot;additionalProperties&quot;: false,
        ///  &quot;properties&quot;: {
        ///    &quot;books&quot;: {
        ///      &quot;type&quot;: &quot;array&quot;,
        ///      &quot;items&quot;: {
        ///        &quot;$ref&quot;: &quot;#/definitions/Book&quot;
        ///      }
        ///    }
        ///  },
        ///  &quot;definitions&quot;: {
        ///    &quot;Book&quot;: {
        ///      &quot;type&quot;: &quot;object&quot;,
        ///      &quot;additionalProperties&quot;: false,
        ///      &quot;properties&quot;: {
        ///        &quot;title&quot;: {
        ///          &quot;type&quot;: &quot;string&quot;
        ///        },
        ///        &quot;autor_names&quot;: {
        ///          &quot;type&quot;: &quot;array&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonSchema {
            get {
                return ResourceManager.GetString("JsonSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syntax = &quot;proto3&quot;;
        ///package Generators.Models;
        ///
        ///message Author {
        ///   int32 BirthYear = 1;
        ///   string FirstName = 2;
        ///   string LastName = 3;
        ///}
        ///message Book {
        ///   repeated Author Authors = 1;
        ///   int32 Pages = 2;
        ///   string Title = 3;
        ///}
        ///message Catalog {
        ///   repeated Book Books = 1;
        ///}
        ///.
        /// </summary>
        internal static string ProtoFile {
            get {
                return ResourceManager.GetString("ProtoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema xmlns:tns=&quot;http://schemas.datacontract.org/2004/07/Generators.Models&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;http://schemas.datacontract.org/2004/07/Generators.Models&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:complexType name=&quot;Catalog&quot;&gt;
        ///    &lt;xs:sequence&gt;
        ///      &lt;xs:element minOccurs=&quot;0&quot; name=&quot;Books&quot; nillable=&quot;true&quot; type=&quot;tns:ArrayOfBook&quot; /&gt;
        ///    &lt;/xs:sequence&gt;
        ///  &lt;/xs:complexType&gt;
        ///  &lt;xs:element name=&quot;Catalog&quot; nillable=&quot;true&quot; type=&quot;tns: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XmlSchema {
            get {
                return ResourceManager.GetString("XmlSchema", resourceCulture);
            }
        }
    }
}
